# Generated by Django 4.2.14 on 2024-07-29 00:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField()),
                ('primary_races', models.JSONField()),
                ('primary_classes', models.JSONField()),
                ('zone_type', models.CharField(blank=True, max_length=80, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField()),
                ('primary_races', models.JSONField()),
                ('primary_classes', models.JSONField()),
                ('zone_type', models.CharField(blank=True, max_length=80, null=True)),
                ('layout', models.TextField(blank=True, null=True)),
                ('contained_objects', models.JSONField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzones', to='game.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('race', models.CharField(max_length=80)),
                ('char_class', models.CharField(max_length=80)),
                ('subclass', models.CharField(blank=True, max_length=80, null=True)),
                ('discipline', models.CharField(blank=True, max_length=80, null=True)),
                ('stats', models.JSONField()),
                ('skills', models.JSONField()),
                ('inventory', models.JSONField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('version', models.IntegerField(default=0)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField(blank=True, null=True)),
                ('backstory', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(null=True)),
                ('xp', models.IntegerField(null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='game.subzone')),
                ('starting_subzone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_starting', to='game.subzone')),
                ('starting_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_starting', to='game.zone')),
            ],
        ),
    ]
