# Generated by Django 4.2.14 on 2024-07-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subzone',
            old_name='layout',
            new_name='layout_description',
        ),
    ]
