# Generated by Django 4.2.14 on 2024-07-29 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_layout_subzone_layout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subzone',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subzone',
            name='primary_classes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subzone',
            name='primary_races',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='zone',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zone',
            name='primary_classes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='zone',
            name='primary_races',
            field=models.JSONField(default=list),
        ),
    ]
