# Generated by Django 4.2.14 on 2024-07-30 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_subzone_last_updated_alter_character_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reward', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('race', models.CharField(max_length=50)),
                ('char_class', models.CharField(max_length=50)),
                ('subclass', models.CharField(blank=True, max_length=50, null=True)),
                ('backstory', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('demeanor', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('can_train_in', models.JSONField(default=list)),
                ('inventory', models.JSONField(default=dict)),
                ('current_subzone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.subzone')),
                ('gives_quests', models.ManyToManyField(blank=True, to='game.quest')),
            ],
        ),
    ]
