# Generated by Django 4.2.14 on 2024-07-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_quest_reward_quest_objectives_quest_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='completed_quests',
            field=models.ManyToManyField(blank=True, related_name='completed_quests', to='game.quest'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_quests',
            field=models.ManyToManyField(blank=True, related_name='current_quests', to='game.quest'),
        ),
    ]
