# Generated by Django 4.2.14 on 2024-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_character_conversation_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_complete',
            field=models.BooleanField(default=False),
        ),
    ]
