# Generated by Django 4.2.14 on 2024-08-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_quest_quest_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='quest_complete',
        ),
    ]
